# Builds RSCS_EDW_NLP_Cost.pptx - a small deck with cost-model slides.
# Designed so you can copy/paste slides into RSCS_EDW_NLP_POC.pptx.

$ErrorActionPreference = 'Stop'

$here    = Split-Path -Parent $MyInvocation.MyCommand.Path
$outPath = Join-Path $here 'RSCS_EDW_NLP_Cost.pptx'

if (Test-Path $outPath) { Remove-Item $outPath -Force }

function RGB ($r,$g,$b) { return ($b -shl 16) -bor ($g -shl 8) -bor $r }
$cRed     = RGB 227 37 38
$cPurple  = RGB 107 73 144
$cGreen   = RGB 76 158 69
$cOrange  = RGB 246 141 45
$cDark    = RGB 34 34 34
$cGray    = RGB 102 102 102
$cMute    = RGB 136 136 136
$cWhite   = RGB 255 255 255
$cBgPanel = RGB 245 243 248

$ppt = New-Object -ComObject PowerPoint.Application
$ppt.Visible = [Microsoft.Office.Core.MsoTriState]::msoTrue
$pres = $ppt.Presentations.Add()
$pres.PageSetup.SlideSize = 15  # 16:9

$msoShapeRectangle   = 1
$msoShapeRoundedRect = 5
$msoTrue  = -1
$msoFalse = 0
$ppLayoutBlank = 12

function Add-Slide {
    param($pres)
    $idx = $pres.Slides.Count + 1
    return $pres.Slides.Add($idx, $ppLayoutBlank)
}

function Set-Background {
    param($slide, [int]$color)
    $slide.FollowMasterBackground = $msoFalse
    $slide.Background.Fill.Visible = $msoTrue
    $slide.Background.Fill.ForeColor.RGB = $color
    $slide.Background.Fill.Solid()
}

function Add-Text {
    param($slide, $left, $top, $width, $height, $text, $size=18, [int]$color=0, [bool]$bold=$false, [int]$align=1, $font='Segoe UI')
    $box = $slide.Shapes.AddTextbox(1, $left, $top, $width, $height)
    $box.Line.Visible = $msoFalse
    $tf = $box.TextFrame
    $tf.WordWrap = $msoTrue
    $tf.MarginLeft = 0; $tf.MarginRight = 0; $tf.MarginTop = 0; $tf.MarginBottom = 0
    $tr = $tf.TextRange
    $tr.Text = $text
    $tr.Font.Name = $font
    $tr.Font.Size = $size
    $tr.Font.Color.RGB = $color
    if ($bold) { $tr.Font.Bold = $msoTrue } else { $tr.Font.Bold = $msoFalse }
    $tr.ParagraphFormat.Alignment = $align
    return $box
}

function Add-Bar {
    param($slide, $left, $top, $width, $height, [int]$color)
    $s = $slide.Shapes.AddShape($msoShapeRectangle, $left, $top, $width, $height)
    $s.Line.Visible = $msoFalse
    $s.Fill.ForeColor.RGB = $color
    $s.Fill.Solid()
    return $s
}

function Add-Footer {
    param($slide, $num, $total)
    Add-Bar $slide 0 525 960 15 (RGB 107 73 144) | Out-Null
    Add-Text $slide 30 528 600 14 'RSCS  -  EDW NLP  -  Cost Model' 9 (RGB 255 255 255) $false 1 | Out-Null
    Add-Text $slide 860 528 80 14 "$num / $total" 9 (RGB 255 255 255) $false 3 | Out-Null
}

$total = 3

# ==========================================================================
# SLIDE 1  -  How it is billed (mental model)
# ==========================================================================
$s = Add-Slide $pres
Set-Background $s $cWhite
Add-Bar $s 0 0 960 6 $cPurple | Out-Null
Add-Text $s 40 30 880 40 'Cost model  -  how the NLP layer is billed' 24 $cDark $true 1 | Out-Null
Add-Bar $s 40 72 80 3 $cPurple | Out-Null
Add-Text $s 40 78 880 22 "You already paid for the runway. The NLP layer just taxis on it." 13 $cGray $false 1 | Out-Null

$buckets = @(
    @("1. NL understanding",    "Fabric Data Agent",         "Capacity Units (CUs) on your existing F-SKU",              "Input:  100 CU-sec / 1K tokens`nOutput: 400 CU-sec / 1K tokens", $cPurple),
    @("2. Query execution",     "Warehouse / Semantic Model", "Same CU pool, different line item",                        "Billed as SQL Query or`nSemantic Model Query",                 $cGreen),
    @("3. Surface layer",       "Power BI / Teams / REST",   "Included in existing Fabric + Power BI entitlements",      "`$0 marginal`n(Copilot Studio external = separate)",           $cOrange)
)

$y = 115
foreach ($b in $buckets) {
    $title = $b[0]; $engine = $b[1]; $where = $b[2]; $how = $b[3]; $col = [int]$b[4]
    $r = $s.Shapes.AddShape($msoShapeRoundedRect, 40, $y, 880, 105)
    $r.Adjustments.Item(1) = 0.1
    $r.Line.ForeColor.RGB = $col
    $r.Line.Weight = 2
    $r.Fill.ForeColor.RGB = $cWhite
    $r.Fill.Solid()

    Add-Bar $s 40 $y 10 105 $col | Out-Null
    Add-Text $s 65 ($y+10)  300 26 $title  15 $col   $true  1 | Out-Null
    Add-Text $s 65 ($y+38)  300 24 $engine 12 $cDark $false 1 | Out-Null
    Add-Text $s 65 ($y+60)  300 40 $where  11 $cGray $false 1 | Out-Null
    Add-Text $s 390 ($y+14) 520 85 $how    13 $cDark $true  1 | Out-Null

    $y += 115
}

Add-Bar $s 40 473 880 2 $cRed | Out-Null
Add-Text $s 40 482 880 20 "Watch-out: the thing that will blow up the bill is not AI. It is bad SQL generated by AI, scanning big unfiltered fact tables." 11 $cDark $true 1 | Out-Null
Add-Text $s 40 502 880 20 "Mitigation: row limits, query timeouts, and semantic model aggregations (all native to Fabric)." 11 $cGray $false 1 | Out-Null

Add-Footer $s 1 $total

# ==========================================================================
# SLIDE 2  -  What it will actually cost us
# ==========================================================================
$s = Add-Slide $pres
Set-Background $s $cWhite
Add-Bar $s 0 0 960 6 $cGreen | Out-Null
Add-Text $s 40 30 880 40 'Cost model  -  what it will actually cost us' 24 $cDark $true 1 | Out-Null
Add-Bar $s 40 72 80 3 $cGreen | Out-Null
Add-Text $s 40 78 880 22 "Marginal cost of adding NLP on top of an existing Fabric capacity." 13 $cGray $false 1 | Out-Null

# --- Per-question math panel (left)
Add-Text $s 40 108 440 24 "Per-question math (Microsoft's own example)" 13 $cDark $true 1 | Out-Null
Add-Bar $s 40 132 440 1 $cMute | Out-Null

$mathRows = @(
    @("Input tokens",       "2,000"),
    @("Output tokens",      "500"),
    @("Formula",            "(2,000 x 100 + 500 x 400) / 1,000"),
    @("Per-request cost",   "400 CU-seconds  =  6.67 CU-minutes"),
    @("F64 daily budget",   "1,536 CU-hours"),
    @("Requests per day",   "~13,800 before capacity exhausted")
)
$y = 140
foreach ($r in $mathRows) {
    $label = $r[0]; $val = $r[1]
    Add-Text $s 50  $y 180 22 $label 11 $cGray $false 1 | Out-Null
    Add-Text $s 235 $y 245 22 $val   11 $cDark $true  1 | Out-Null
    $y += 22
}
Add-Text $s 40 278 440 30 "Real questions land 3K-8K input tokens once schema context is injected." 10 $cMute $false 1 | Out-Null
Add-Text $s 40 293 440 30 "Still negligible on any SKU >= F8." 10 $cMute $false 1 | Out-Null

# --- Scenario table (right)
Add-Text $s 500 108 420 24 "Scenario estimates" 13 $cDark $true 1 | Out-Null
Add-Bar $s 500 132 420 1 $cMute | Out-Null

$scenarios = @(
    @("Light pilot",      "5 users x 10 q/day",  "~$0 marginal", $cGreen),
    @("Moderate adoption", "50 users x 20 q/day", "~$0 marginal", $cGreen),
    @("Heavy adoption",    "500 users self-serve", "+1 SKU step`n+`$1.5K-3K/mo reserved", $cOrange)
)
$y = 140
foreach ($sc in $scenarios) {
    $name = $sc[0]; $vol = $sc[1]; $cost = $sc[2]; $col = [int]$sc[3]
    Add-Bar $s 500 $y 6 45 $col | Out-Null
    Add-Text $s 515 $y       200 22 $name 12 $cDark $true  1 | Out-Null
    Add-Text $s 515 ($y+22)  200 22 $vol  10 $cGray $false 1 | Out-Null
    Add-Text $s 720 $y       200 45 $cost 11 $col   $true  1 | Out-Null
    $y += 52
}

# --- F-SKU anchor table
Add-Text $s 40 325 880 24 "Fabric F-SKU anchors (PAYG, ~EU pricing)" 13 $cDark $true 1 | Out-Null
Add-Bar $s 40 349 880 1 $cMute | Out-Null

Add-Bar $s 40 358 880 26 $cPurple | Out-Null
Add-Text $s 55  362 100 22 "SKU"         11 $cWhite $true 1 | Out-Null
Add-Text $s 175 362 150 22 "Hourly"      11 $cWhite $true 1 | Out-Null
Add-Text $s 345 362 180 22 "Monthly PAYG" 11 $cWhite $true 1 | Out-Null
Add-Text $s 540 362 360 22 "Typical fit" 11 $cWhite $true 1 | Out-Null

$skus = @(
    @("F2",  "~EU0.42/hr",  "~EU300/mo",   "Dev / test only",                                 $true),
    @("F8",  "~EU1.70/hr",  "~EU1,200/mo", "Small team pilot",                                 $false),
    @("F64", "~EU13.50/hr", "~EU9,700/mo", "Production - includes Power BI Pro for viewers",   $true)
)
$y = 384
foreach ($row in $skus) {
    $sku = $row[0]; $hr = $row[1]; $mo = $row[2]; $fit = $row[3]; $alt = [bool]$row[4]
    if ($alt) { Add-Bar $s 40 $y 880 24 $cBgPanel | Out-Null }
    Add-Text $s 55  ($y+2) 100 22 $sku 11 $cDark  $true  1 | Out-Null
    Add-Text $s 175 ($y+2) 150 22 $hr  11 $cDark  $false 1 | Out-Null
    Add-Text $s 345 ($y+2) 180 22 $mo  11 $cDark  $false 1 | Out-Null
    Add-Text $s 540 ($y+2) 360 22 $fit 11 $cGray  $false 1 | Out-Null
    $y += 24
}

Add-Bar $s 40 468 880 2 $cPurple | Out-Null
Add-Text $s 40 476 880 20 "1-year reservation: approximately 41% off PAYG. F64 reserved drops to approximately EU5,700/mo." 11 $cDark $true 1 | Out-Null
Add-Text $s 40 496 880 20 "Capacity can be paused. For a pilot, run only during business hours - halves the bill." 11 $cGray $false 1 | Out-Null

Add-Footer $s 2 $total

# ==========================================================================
# SLIDE 3  -  Things you should know
# ==========================================================================
$s = Add-Slide $pres
Set-Background $s $cWhite
Add-Bar $s 0 0 960 6 $cOrange | Out-Null
Add-Text $s 40 30 880 40 'Cost model  -  things you should know' 24 $cDark $true 1 | Out-Null
Add-Bar $s 40 72 80 3 $cOrange | Out-Null
Add-Text $s 40 78 880 22 "Six points worth raising out loud before anyone asks." 13 $cGray $false 1 | Out-Null

$points = @(
    @("No per-seat license for Data Agent",  "Users consume via existing Power BI / Fabric entitlements. No `$30/user/month Copilot seat trap.",          $cGreen),
    @("Scales with usage, not headcount",    "1,000-person org where 20 use it costs the same as a 20-person org where all 20 use it.",                   $cGreen),
    @("Two line items to monitor",           "AI Query (tokens) and SQL / Semantic Model Query (execution). Both visible in the Fabric Capacity Metrics App.", $cPurple),
    @("Capacity is pausable",                "Pause outside business hours for pilots. Instant ~50% cut. No code changes needed.",                         $cPurple),
    @("Reservation math matters",            "At production scale, 1-year reserved is approximately 41% cheaper than PAYG. Factor in before comparing to DIY.", $cOrange),
    @("vs. DIY Azure OpenAI",                "GPT-4o direct: `$2.50 in / `$10 out per 1M tokens. Cheaper per token - but you own grounding, security, prompt mgmt, ops. Fabric bundles all of it.", $cRed)
)

$y = 115
foreach ($p in $points) {
    $title = $p[0]; $body = $p[1]; $col = [int]$p[2]
    $r = $s.Shapes.AddShape($msoShapeRoundedRect, 40, $y, 880, 60)
    $r.Adjustments.Item(1) = 0.2
    $r.Line.ForeColor.RGB = $col
    $r.Line.Weight = 1.5
    $r.Fill.ForeColor.RGB = $cWhite
    $r.Fill.Solid()
    Add-Bar $s 40 $y 8 60 $col | Out-Null
    Add-Text $s 65 ($y+8)  820 22 $title 13 $col   $true  1 | Out-Null
    Add-Text $s 65 ($y+30) 820 30 $body  11 $cGray $false 1 | Out-Null
    $y += 68
}

Add-Bar $s 40 493 880 2 $cPurple | Out-Null
Add-Text $s 40 500 880 25 "To verify before the meeting: exact F-SKU price in your Azure region, and current CU headroom (Fabric Capacity Metrics App, last 30 days)." 11 $cDark $true 1 | Out-Null

Add-Footer $s 3 $total

# Save
$pres.SaveAs($outPath)
$pres.Close()
$ppt.Quit()

[System.Runtime.InteropServices.Marshal]::ReleaseComObject($pres) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ppt) | Out-Null
[System.GC]::Collect() | Out-Null
[System.GC]::WaitForPendingFinalizers() | Out-Null

Write-Host "Wrote $outPath"
